# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Patient')),
            ],
        ),
    ]
