# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20171030_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='startTime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
