# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20171030_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(default=datetime.time(12, 10)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
