# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_auto_20171030_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnostics',
            field=models.CharField(default='Data', max_length=100000),
        ),
    ]
