# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_status',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
