# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_appointment_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='module.Appointment_Status'),
            preserve_default=False,
        ),
    ]
