# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0012_auto_20171121_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Appointment')),
            ],
        ),
        migrations.AddField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.prescription_list'),
        ),
        migrations.AddField(
            model_name='prescription_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Product'),
        ),
    ]
