# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0015_auto_20171121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_req',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Prescription_List'),
        ),
    ]
