# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_auto_20171205_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(default=0, max_length=70)),
                ('time_stemp', models.DateTimeField(auto_now_add=True)),
                ('paid', models.CharField(default=0, max_length=70)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Appointment')),
            ],
        ),
        migrations.AlterField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Prescription_List'),
        ),
    ]
