# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0018_auto_20171205_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Prescription_List'),
        ),
    ]
