# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0020_auto_20171205_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='paid',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Bill_status'),
        ),
        migrations.AlterField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Prescription_List'),
        ),
    ]
