# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0027_auto_20171205_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default=0, max_length=10000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Bill_status'),
        ),
        migrations.AlterField(
            model_name='prescription_details',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Prescription_List'),
        ),
    ]
